### ISSUE TITLE
Is it possible to set the Ident attribute in CurrentCellXf?

### ISSUE THREAD

**Issue by thiagossrs** [rabanti-github/NanoXLSX#11]
Is it possible to set the Ident attribute for alignment in CurrentCellXf?

In the Excel Styles.xml would be something like:

`	<cellXfs count="4">
		<xf numFmtId="0" fontId="0" fillId="0" borderId="0" xfId="0"/>
		<xf numFmtId="14" fontId="0" fillId="0" borderId="0" xfId="0" applyNumberFormat="1"/>
		<xf numFmtId="164" fontId="0" fillId="0" borderId="0" xfId="0" applyNumberFormat="1"/>
		<xf numFmtId="0" fontId="0" fillId="0" borderId="0" xfId="0" applyAlignment="1">
			<alignment horizontal="left" indent="3"/>
		</xf>
	</cellXfs>`

**Comment by rabanti-github** [comment]
Do you mean "indent"?
This is currently not implemented. But it's probably easy to add.
Let me make a quick test.

**Comment by rabanti-github** [comment]
I missed to hit the "Comment" button for the previous comment :-)

Here is a preview of the indent feature
https://github.com/rabanti-github/NanoXLSX/tree/dev

I have to check some other changes until I release the new version. But should be done by today or tomorrow.

**Comment by rabanti-github** [comment]
The new feature is implemented in v1.5
The NuGet package is already available.

Thank you for pointing out the missing feature.
Please let me know if something is not behaving as expected.

**Comment by thiagossrs** [comment]
You're really fast.
Thank you for all of your effort, and congratulations for a great product.
I use your library in several projects.
Thank you.

**Comment by rabanti-github** [comment]
You're welcome.
There is still some effort to make. A topic of the ongoing rewrite of the library is (among others) unit-testing, inline-formatting, comments, conditional formatting. But fore these features, the library must become way more modular (work in progress).

Anyway, I will close the Issue for now. Please re-open it or create a new issue, if there are any problems.
