### ISSUE TITLE
Property "Hidden" in the sheet object is not correct

### ISSUE THREAD

**Issue by javos79** [rabanti-github/NanoXLSX#21]
**Excelfile**

Create two sheets (Name: "Visible" and "Invisible")
Hide the sheet named "Invisible" (https://support.microsoft.com/en-us/office/hide-or-unhide-worksheets-69f2701a-21f5-4186-87d7-341a8cf53344)
Save the excelfile as "excel_with_two_sheets.xlsx"

**Dependency:**
```
  <ItemGroup>
    <PackageReference Include="NanoXLSX" Version="1.8.1" />
  </ItemGroup>
```

**Minimal Code**

```
using System;
using NanoXLSX;

namespace nanoxlsx_minimal
{
    internal class Program
    {
        static void Main(string[] args)
        {
            var workBook = Workbook.Load("excel_with_two_sheets.xlsx");

            foreach (var sheet in workBook.Worksheets)
            {
                Console.WriteLine($"{sheet.SheetName}: Hidden: {sheet.Hidden}");
            }
        }
    }
}
```

**Current result**

```
Visible: Hidden: False
Invisible: Hidden: False
```

Both sheets return "false" for the "Hidden" property.

**Comment by rabanti-github** [comment]
Hello
Thank you for your report. I will have a look into this.
The reader functionality is currently under complete renovation in the dev branch.
Reading this property is probably not implemented yet. I will add it to the backlog.
If an implementation is not deviating too much between dev and the current master branch, I will publish a hotfix as soon as possible. But more about that after I looked thoroughly into your issue.

**Comment by rabanti-github** [comment]
A fix is already available on the branch dev-temp: https://github.com/rabanti-github/NanoXLSX/commit/f2763be83f04412a09ca099719c051bc57b443ef
Merging into master, as well as a new release will be done probably the next few days

**Comment by javos79** [comment]
Awesome!
Thx

**Comment by rabanti-github** [comment]
The Release v1.8.2 was published today. The Nuget package should be available in some minutes.
Furthermore, additional features of the reader are currently under development.
Please let me know if something does not work as expected.
Thank you again for the report.
