### ISSUE TITLE
Are there plans for vba macro support

### ISSUE THREAD

**Issue by gnobbi** [rabanti-github/NanoXLSX#22]
Hi,

First of all very nice Library and good interface 😊.

Do you plan to implement to add vba macro support? 

Like https://github.com/EPPlusSoftware/EPPlus/wiki/VBA

Thanks alot

**Comment by rabanti-github** [comment]
Hello,
Thank you.
Currently VBA support is not on the roadmap.
Pending is near-feature-complete reader support for styles, as well as In-line styling of cells and extensive code coverage by unit tests.
However, the next major version will have probably a better modularity. An add-on package for VBA support could be possible.

**Comment by rabanti-github** [comment]
I will close this issue for now.
If modularity is implemented, the topic may be come back to the surface.
Thank you again for the suggestion.
