### ISSUE TITLE
The sheet cloning method

### ISSUE THREAD

**Issue by Ryba1986** [rabanti-github/NanoXLSX#23]
Can you implement a method to clone an existing sheet with a new name?

**Comment by rabanti-github** [comment]
Hello
This is probably quite easy to achieve. However there is a set of other worksheet data that must be cloned beside cells.
But I can do it on the backlog.

**Comment by rabanti-github** [comment]
Hi,
Worksheet cloning is now possible with just released version 2.0.0

Thanks again for the request.

**Comment by Ryba1986** [comment]
Great news! I will tray use it.
