### ISSUE TITLE
String read as date.

### ISSUE THREAD

**Issue by thiagossrs** [rabanti-github/NanoXLSX#3]
I'm reading a spreadsheet with this:

            Dim ws As Worksheet = wb.Worksheets(0)
            Dim Cx As Dictionary(Of String, Cell) = ws.Cells()

In the spreadsheet the cell has this value: 1.1.2.03.00001

I need to read as a text, but the Cells() return it as a date.

Is it possible to force Cells to read in the specific format?

**Comment by thiagossrs** [comment]
I changed the ResolveCellData, recompiled and managed to make it work. I made everything return as a string. For me it worked.

But it would be nice if the library correctly return the date types.

**Comment by rabanti-github** [comment]
Can you explain your use-case?
Do you provide this value 1.1.2.03.00001 as date in the Excel worksheet, or is it already Text (in Excel)?
If it is a date, then the string output is difficult to predict, since the XLSX file stores a date internally in a more or less neutral format. And there are literally thousands of date-time formats as possible outputs.
However, if it is text and NanoXLSX interprets it automatically as a date, then it looks like a bug.

Can you provide an example file, and maybe the code snippet that worked for your use-case?

Thank you in advance

**Comment by thiagossrs** [comment]
Sorry, i did not see your question. I'll send you an example file with a snippet.
Thank you.

**Comment by thiagossrs** [comment]
Workbook wb = Workbook.Load("D:\\Temp\\DataErr.xlsx");
            Worksheet ws = wb.Worksheets[0];
            Dictionary<string, Cell> Cx = ws.Cells;
            Console.WriteLine(Cx["A1"].Value);
            Console.WriteLine(Cx["A2"].Value);
            Console.WriteLine(Cx["A3"].Value);
            Console.WriteLine(Cx["A4"].Value);
            Console.WriteLine(Cx["A5"].Value);

[DataErr.xlsx](https://github.com/rabanti-github/NanoXLSX/files/4552023/DataErr.xlsx)

**Comment by rabanti-github** [comment]
Hm... Odd. A1 and A2 are defined as text, what seems to be right.
But A3, A4 and A5 are defined as dates, what obviously is not the case.
I have to analyze this. Seems to be a bug.

**Comment by rabanti-github** [comment]
It seems that the cells A3 to A5 were originally dates. Then, the cell values were override with text. However, Excel kept the date format, although it has no impact on the text.
NanoXLSX interprets cells according to the assigned cell style. This is not sufficient under the described circumstances.
I have to add an additional check. Nevertheless, there is another issue in the same area with Times. I will introduce a simple style reader (at least for NumberFormats) to handle this.

**Comment by silvioburger** [comment]
Hello
I have found a solution that works for me. I made this changes to ResolveCellData Methode in WorksheetReader.cs:

`
if (**type == null &&** style != null && style == "1") // Date must come before numeric values
      {
        tuple = GetDateValue(value);
        if (tuple.IsValid)
        {
          cell = new Cell(tuple.Data, Cell.CellType.DATE, address);
        }
        else
        {
          cell = new Cell(value, Cell.CellType.STRING, address);
        }
      }
      **else if (type == null && style != null && style == "3") // Time
      {
        tuple = GetDateValue(value);
        if (tuple.IsValid)
        {
          cell = new Cell(((DateTime)tuple.Data).TimeOfDay, Cell.CellType.DATE, address);
        }
        else
        {
          cell = new Cell(value, Cell.CellType.STRING, address);
        }
      }**
`

@rabanti: Since I am not an Excel expert, I would like to get your opinion whether this is good.

**Comment by rabanti-github** [comment]
This was also my first thought, and this will probably be working in 99% of all cases.
However, the assumption of style no. 3 as an indicator for time formatting relies on the fact that nothing (Excel or a writer library) has tampered with the style document of the workbook. The actual formatting for time is encoded in the number format, which is , for instance, 21 for "h:mm:ss". By default style 3 has this number format.

The "best" solution is to:
1. Read the style document (styles.xml)
2. Parse the style definitions (break up into ist references)
3. Resolve the number formats of the style definitions
4. Match the resolved style definitions (with assigned number formats) with the style attributes of the cells.

I have planned to do this, but found not time yet. But I will do it hopefully soon.
As a workaround, I would recommend your fix.

**Comment by rabanti-github** [comment]
Resolved with the (slightly adapted) proposed fix in version 1.3.6.
A final fix (proper style reader) is still pending.

The nuget package is available in some minutes.
Thank you all for your contribution.
