### ISSUE TITLE
Set cell value

### ISSUE THREAD

**Issue by Ryba1986** [rabanti-github/NanoXLSX#32]
How can i set the value of a cell retrieved with the `Worksheet.GetCell` metod? I try set Value property but not work

**Comment by rabanti-github** [comment]
Hi,
A cell object is currently more or less a read-only object.
I assume you want to adjust data from a loaded workbook.
As a workaround, you can do the following:
- Get the cell "cell1"
- Get the address of the cell
- Add a new cell in in your worksheet with the new value and the address of "cell1". This will overrode the old cell
`worksheet.AddCell(newValue, cell1.CellAddress);` 

It is probably an enhancement if the value can be set directly.

**Comment by Ryba1986** [comment]
I think is a good option. Before that the Value property of Cell object should by read only.

**Comment by rabanti-github** [comment]
Hi,
Cell values can now be set by the Value property of the cell.
This was possible earlier too, but a type check was missing. This was added now.
The fix was released with v2.0.2.
The NuGet package should be available in a few minutes

**Comment by rabanti-github** [comment]
I will close this issue for now.
Please do not hesitate to re-open or file a new one, if further problems occur.
Thank you for the report.
