### ISSUE TITLE
Attempting to freeze the first row of the spreadsheet

### ISSUE THREAD

**Issue by kchanninggithub** [rabanti-github/NanoXLSX#33]
I am currently attempting to freeze the first row of the spreadsheet I am creating using NanoXLSX. 

Here is the psuedo code for what I am doing...

* Create a new Cell object passing the cell value and CellType into the constructor.
* Create a new Style object setting the Fill to a hex string and the FillType to fillColor.
* Call the Style method of the cell passing in the style object, created above, and setting unmanaged to true, I have also tried false.
* Call the SetCellLockState of the cell passing in 'true', of isLocked, and 'false', for isHIdden. NOTE: when I debug my code I am unable to see any properties, in my cell object, that indicate that the cell is marked as being locked.
* Add the cell to the worksheet, by way of the AddeCell method, passing in the parameters of cell, my current column value, my current row value.

When my spreadsheet is generated all of the styles have been applied and the subsequent row data, which is added after the above code is run, appears as expected. However, the top row, the on in which I have place my column headers, is not locked.

When I go throught the available methods for both the cell and the row, it is only the cell which seems to contain a method that deals with locking. With this being the case, I am getting the impression that the SetCellLockState is not doing what one would think it should.

Am  I going about this the wrong way?

**Comment by rabanti-github** [comment]
Hi,
Have you tried with something like this?:
`workbook.CurrentWorksheet.SetHorizontalSplit(1, true, new Address("A2"),Worksheet.WorksheetPane.topLeft);`
For pane splitting and freezing are several methods available. This should not be a styling or window protecting/locking issue.

**Comment by kchanninggithub** [comment]
Thank-you, I will give this a try over the weekend.

**Comment by kchanninggithub** [comment]
Thank-you, worked great.

**Comment by rabanti-github** [comment]
Super! Since this is obviously a very common use case  (top row, first column, or both), I consider to add a convenience function for that in the next version
