### ISSUE TITLE
Content corrupted on Worksheet rename

### ISSUE THREAD

**Issue by CoolDixon** [rabanti-github/NanoXLSX#34]
Hi Rabanti,

I just catch an other weird bug. If I rename a worksheet with this code:
`
string Filename = @"C:\_Local\Sample.xlsx"; 
Workbook Wb = Workbook.Load(Filename); 
Wb.GetWorksheet("Sheet1").SetSheetName("NewSheetName"); 
Wb.Filename = Filename; 
Wb.Save();
`
I get the dates corrupted.

Before:
![Screenshot 2022-10-02 at 13 05 10](https://user-images.githubusercontent.com/5981332/193451588-678894dc-8907-40fb-9230-9cf972cd6aab.png)

After:
![Screenshot 2022-10-02 at 13 06 59](https://user-images.githubusercontent.com/5981332/193451623-c5780325-9c5e-4c67-b2b0-4dcd803825c3.png)

[Sample.xlsx](https://github.com/rabanti-github/NanoXLSX/files/9692351/Sample.xlsx)

**Comment by rabanti-github** [comment]
Hi,
What is your system locale, where the library is running? Other than "en-US"?

**Comment by rabanti-github** [comment]
Hi, can you quickly try the attached NuGet package out?
This should fix any I18N-parsing issue. If it is working, I will do some maintenance work and the release the patch ASAP.
Thank you in advance
[Debug.zip](https://github.com/rabanti-github/NanoXLSX/files/9692776/Debug.zip)

**Comment by CoolDixon** [comment]
It works!

![image](https://user-images.githubusercontent.com/5981332/193504399-575fdda0-f6d3-41b9-b655-822569bb654b.png)

my locale is "es-ES"

**Comment by rabanti-github** [comment]
Hi,
It was not an issue of renaming but of parsing numbers when reading and then saving the file again. The dates are internally stored as floats (OADate, starting at 1900-01-01). .NET is parsing such numbers and also date/time representations - if not stated other - in the current locale of the running computer. Therefore it may mess up decimal points and number separators. Same applies to ToString, by the way.
I thought I have already eliminated all of the unspecified parser code, but there were still parts in the reader remaining.
Maybe I integrate localization unit tests.

I will release the patched version soon.
Thank you for testing the preview.

**Comment by rabanti-github** [comment]
I will close this issue for now.
Please do not hesitate to re-open or file a new one, if further problems occur.
Once again, thank you very much for the report and testing
