### ISSUE TITLE
Multiple selections causing FormatException: The cell range () is malformed and could not be resolved

### ISSUE THREAD

**Issue by CSitterlee** [rabanti-github/NanoXLSX#39]
**Bug description**
In a xlsx where multiple ranges are selected, Workbook.Load() raises an FormatException: The cell range (...) is malformed and could not be resolved.

You can reproduce the error with the attached: [Test.xlsx](https://github.com/rabanti-github/NanoXLSX/files/9901827/Test.xlsx)
It is just an empty workbook where the cells A1:A3 and A6:A8 are selected.

**Sample Code**
var wb = NanoXLSX.Workbook.Load(@"C:\Temp\Test.xlsx");

**Expected behavior**
NanoXLSX should be able to read the file.

**Environment (please complete the following information):**
OS: Window 10
.NET framework: .NET 6
System locale: de-DE
Version of NanoXLSX:  2.0.4

**Comment by rabanti-github** [comment]
Hi,
Thanks for the report. I have never considered that.
The fix of this is quite easy. But an adaption of the SelectedCells property is necessary. It must be a List of Ranges, therefore. And the function to set selected cells must be adapted as well.
I will need probably some days for that (adaption, testing, documentation, package deployment, synchronization between the libraries).

**Comment by CSitterlee** [comment]
Of course, take your time. As a workaround, I just took the first range adress (separated with a space character) and discarded the rest. So at least it doesn't crash anymore...

My fix looks like this in WorksheetReader.GetSheetView(XmlDocument xmlDocument) around line 218:

var ranges = attribute.Split(' ');
this.SelectedCells = new Range(ranges[0]);

**Comment by rabanti-github** [comment]
Yes, that's exactly the easy fix :-)
So, SelectedCells will be List<Range> instead of Range? in the next minor version, I am working on.
Fixing the unit tests and backport to PicoXLSX and NanoXLSX4j will take some time

**Comment by rabanti-github** [comment]
Hi, 
multiple selected cells should now be handled with release v2.1.0, using the AddSelectedCells(...) methods and the SelectedCellRanges  property.
Thanks again for the report.
Please do not hesitate to reopen or file a new bug report if something is not working as expected

**Comment by rabanti-github** [comment]
I will close the issue for now. Thank you again
