### ISSUE TITLE
AddNextCellFormula not applying style.

### ISSUE THREAD

**Issue by thiagossrs** [rabanti-github/NanoXLSX#4]
There is a bug in the AddNextCellFormula method, it does not apply the style supplied in the method.

There is an easy fix.

        public void AddNextCellFormula(string formula, Style style)
        {
            Cell c = new Cell(formula, Cell.CellType.FORMULA, currentColumnNumber, currentRowNumber, this);
            AddNextCell(c, true, null);
        }

Should be:

        public void AddNextCellFormula(string formula, Style style)
        {
            Cell c = new Cell(formula, Cell.CellType.FORMULA, currentColumnNumber, currentRowNumber, this);
            AddNextCell(c, true, style);
        }

**Comment by rabanti-github** [comment]
Thank you for the report and the fix.
The library was updated to version 1.3.6.
The nuget package should be available in some minutes
