### ISSUE TITLE
Protected worksheet causes System.FormatException: Input string was not in a correct format

### ISSUE THREAD

**Issue by CSitterlee** [rabanti-github/NanoXLSX#40]
**Bug description**
I have a workbook with protected worksheets from an external source. I don't know how the file was processed, but it is opening without errors in Microsoft Excel 365 (current). NanoXLSX (2.0.4 and current github-version) throws an:

System.FormatException
  HResult=0x80131537
  Nachricht = Input string was not in a correct format.
  Quelle = System.Private.CoreLib
  Stapelüberwachung:
   bei System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   bei System.Number.ParseInt32(ReadOnlySpan`1 value, NumberStyles styles, NumberFormatInfo info)
   bei System.Int32.Parse(String s, IFormatProvider provider)
   bei NanoXLSX.LowLevel.ReaderUtils.ParseInt(String rawValue) in C:\github\NanoXLSX\NanoXLSX\LowLevel\ReaderUtils.cs: Zeile110
   bei NanoXLSX.LowLevel.WorksheetReader.ManageSheetProtection(XmlNode node, SheetProtectionValue sheetProtectionValue) in C:\github\NanoXLSX\NanoXLSX\LowLevel\WorksheetReader.cs: Zeile331
   bei NanoXLSX.LowLevel.WorksheetReader.GetSheetProtection(XmlDocument xmlDocument) in C:\github\NanoXLSX\NanoXLSX\LowLevel\WorksheetReader.cs: Zeile297
   bei NanoXLSX.LowLevel.WorksheetReader.Read(MemoryStream stream) in C:\github\NanoXLSX\NanoXLSX\LowLevel\WorksheetReader.cs: Zeile187
   bei NanoXLSX.LowLevel.XlsxReader.Read() in C:\github\NanoXLSX\NanoXLSX\LowLevel\XlsxReader.cs: Zeile136
   bei NanoXLSX.Workbook.Load(String filename, ImportOptions options) in C:\github\NanoXLSX\NanoXLSX\Workbook.cs: Zeile907
   bei Demo.Program.Main(String[] args) in C:\github\NanoXLSX\Demo\Program.cs: Zeile33

on loading. (After removing the try/catch-blocks in XlsxReader.Read() and WorksheetReader.Read())

The sheet1.xml contains the following element:
<sheetProtection sheet="false" objects="false" scenarios="false" formatCells="false" formatColumns="false" formatRows="false" insertColumns="false" insertRows="false" insertHyperlinks="false" deleteColumns="false" deleteRows="false" selectLockedCells="false" sort="false" autoFilter="false" pivotTables="false" selectUnlockedCells="false"/>

So it looks like NanoXLS is failing on converting the "false" expressions into an int.

I am not sure how there "false"-expressions where generated. But NanoXLS could easy accept those in 

ReaderUtils.ParseInt():

        internal static int ParseInt(String rawValue)
        {
            if (rawValue == "false") return 0;
            if (rawValue == "true") return 1;
            return int.Parse(rawValue, CultureInfo.InvariantCulture);
        }

**Comment by rabanti-github** [comment]
Hi,
Thank you for the report.
Unfortunately, I can do absolutely nothing without a sample file in this case.
I don't know what was passed to the function and I cannot assume it without the risk of breaking other things.
If you cannot disclose a sample file, try at least to extract the corresponding worksheet xml file (probably sheet1.xml), using a tool like [MediaExtractor](https://github.com/rabanti-github/Media-Extractor).
Thank you in advance.

**Comment by rabanti-github** [comment]
Hi,
Thank you for that.
Yes, of course. You can send me a message to github_ät_rabanti_DOT_ch
I speak also German :-)
Thank you in advance.

**Comment by rabanti-github** [comment]
Hi,
Thank you for the sample. I am working already on a fix for this.

**Comment by rabanti-github** [comment]
Hi,
This issue should also be fixed with release v2.1.0.
Please reopen this issue or file a new one. if something is not working as expected.
Thank you

**Comment by rabanti-github** [comment]
I will close the issue for now, thank you
