### ISSUE TITLE
Chartsheet break the reader

### ISSUE THREAD

**Issue by iivmok** [rabanti-github/NanoXLSX#44]
**Bug description**
Opening an xlsx with a chartsheet throws a null exception.

**Steps To Reproduce**
An excel file I can't provide, sorry.

in `NanoXLSX.LowLevel.XlsxReader.Read()` there's a line get a sheet entry stream `MemoryStream entryStream3 = this.GetEntryStream(name, archive);`, which returns null since this sheet does not actually exist in worksheets but in chartsheets.
workbook.xml does list it though in <sheets>.

**Comment by rabanti-github** [comment]
Hi,
Thanks for the bug report and the PR. Looks good so far. Only one small issue with the test.
I will do the administrative tasks (Some comments, Release Notes, Package, Porting to NanoXLSX4j, etc.) ASAP

**Comment by rabanti-github** [comment]
Sorry, this will take some days more. I just recognized that now over 500 Tests are failing on dev-pr.
I have to fix this before releasing

**Comment by iivmok** [comment]
No worries, I understand

**Comment by rabanti-github** [comment]
Version 2.1.1 of NanoXLSX was just releases.
The NuGet package is already available.
Thanks again for the contribution and the fix.
Please reopen or create a new Issue, if something is not working as expected.
