### ISSUE TITLE
Fill.ValidateColor(): misleading exception message

### ISSUE THREAD

**Issue by JarrenLong** [rabanti-github/NanoXLSX#50]
When Fill.ValidateColor() is called (internally) with an invalid-length hex code, the error message within the exception indicates that 'A valid value must contain six hex characters', however this message does not respect  that there may be an alpha value specified. Error message should be updated to output the value of the 'num' variable used in the length check instead of the hardcoded 'six' in the string.

**Pseudo-Sample Code**
```
try {
	// Get the cell and set the background color
	Cell c = ws.GetCell(0, 0);

	// This works as expected (8-char hex string)
	c.CellStyle.CurrentFill.BackgroundColor = string.Format("FF{0:X2}{1:X2}{2:X2}", fmt.BackColor.R, fmt.BackColor.G, fmt.BackColor.B);

	// Generates exception with message (6-char hex string)
	c.CellStyle.CurrentFill.BackgroundColor = string.Format("{0:X2}{1:X2}{2:X2}", fmt.BackColor.R, fmt.BackColor.G, fmt.BackColor.B);

} catch (StyleException ex) {
	// Generates exception with message
	int brk = 0;
}
```

**Comment by rabanti-github** [comment]
Hi,
Thank you for the report and sorry about the delay.
You are correct, the message should be updated.
I think this should be sufficient, since I assume that it is clear that 8 characters contains two alpha characters:
```
int length = useAlpha ? 8 : 6;
if (hexCode.Length != length)
{
    throw new StyleException("The value '" + hexCode + "' is invalid. A valid value must contain " + length + " hex characters");
}
```
If this is OK for you, I will update ASAP. However, currently, other changes are pending. Therefore it may take some days until an update is released.

**Comment by JarrenLong** [comment]
Looks perfect, and thank you!

**Comment by rabanti-github** [comment]
Was completed with release v2.3. I will close this issue for now
