### ISSUE TITLE
Merge .NET Framework and .NET Standard/Core projects

### ISSUE THREAD

**Issue by JarrenLong** [rabanti-github/NanoXLSX#66]
**Is your feature request related to a problem? Please describe.**
When compiling NanoXLSX, it is annoying having to have separate .csproj project files for .NET Framework builds and .NET Standard/Core that need to be maintained separately.

**Describe the solution you'd like**
Merge the .NET Framework project files into the .NET Standard/Core projects so that NanoXLSX can be compiled and maintained more efficiently.

**Additional context**
Pull request incoming

**Comment by rabanti-github** [comment]
The new structure was applied and a package v2.5.2 was released (no changes expected by the new project structure).
Thanks again for the contribution
