### ISSUE TITLE
Exception loading workbook.

### ISSUE THREAD

**Issue by thiagossrs** [rabanti-github/NanoXLSX#7]
When trying to read a workbook:

    Dim wb As Workbook = Workbook.Load(Caminho)

An exception is throw:

    IOException: The XML entry could not be read from the input stream. Please see the inner exception:
    ArgumentException: Not a legal OleAut date.

[error.xlsx](https://github.com/rabanti-github/NanoXLSX/files/5123598/error.xlsx)

**Comment by rabanti-github** [comment]
This sounds like a localization issue. Do you have saved this workbook on a system with another calendar than Gregorian?
Can you provide this or a similar file with this issue?

Another possibility is that the file was locked by Excel (a Worksheet is locked in the file system by Excel, when loaded). However, this is normally another exception (access denied).

**Comment by rabanti-github** [comment]
OK, I see the problem. It is again the date parsing issue what I tried to solve with the last workaround-release.
The two numbers "NF NUM" and "SALDO" are tried to be parsed as date (Style 3). However, "NF NUM" is far to big (would be the year 30639 a.D.) for a OAdate, and "SALDO" is negative, which is also invalid as OAdate.
It looks like we have here exactly the case, when Style 3 is not the format for date. This can finally only be solved by a proper style parser.
I can deliver a hotfix (hopefully today or tomorrow) for it and have to implement the style reader afterwards.

**Comment by thiagossrs** [comment]
Thank you.

**Comment by rabanti-github** [comment]
There is a fix available on the Dev branch.
The crash should not occur anymore. Furthermore, I introduced import options to define the target type of columns (override).

However...
I saw that the problems with dates and times are much more volatile as initially assumed. There is no guarantee that style 1 is always for dates and style 3 for times. Tests with several versions of Excel lead to different results.
Therefore, I have to implement this style reader, at least in a rudimentary form. Otherwise, reading values is unreliable.

Please bear with me. I am working on it.

**Comment by thiagossrs** [comment]
The import option should help a lot.

Thank you for all of your work.

I’ll wait for the style reader. Please let me know anyway I can help.

**Comment by rabanti-github** [comment]
I just released version 1.4 of NanoXLSX. The following changes were made:
* Implemented a style reader to determine dates and times (however, custom formats are not considered at the moment)
* Added type TIME in reader and writer to cover time formats. This type is represented by [TimeSpan](https://docs.microsoft.com/en-us/dotnet/api/system.timespan?view=netcore-3.1) objects
* Changed the namespace 'Styles' to 'NanoXLSX.Styles' to be more consistent
* Updated examples and documentation

The Nuget package was releases some minutes before and should already be available.
The style reader does only consider number formats at the moment (important to determine dates and times). Other information like borders, fonts or fills are neglected. However, custom formats are recognized and may be processed manually.

The writer-only library '[PicoXLSX](https://github.com/rabanti-github/PicoXLSX)' does nor handle TIME at the  moment. The new writer functionality will be back-ported to the library ASAP.

I have to admit, that the style reader was not tested thoroughly. However, initial test looks promising. Please don't hesitate to report any issue with the re-implementation of the reader.

**Comment by thiagossrs** [comment]
Thank you very much.
I'm performing several tests. I'll let you know.

**Comment by thiagossrs** [comment]
Everything seems to be working fine.
Thank you.

**Comment by rabanti-github** [comment]
I hope, it is OK, when I close this issue now. I will publish probably a small maintenance release soon, but nothing functional will change with this (mainly code cleanup).
Please reopen the issue, if any problems occur with the reader in context of dates, or open a new issue.
Thank you for the report and the tests.
